const siteData = {
  statements: [
    { title: "Proposito", text: "Transformando oportunidades em valor por meio da inovacao." },
    { title: "Visao", text: "Ser referencia global em inovacao e parceiro de solucoes." },
    {
      title: "Missao",
      text: "Projetar e desenvolver sistemas, fluxos e processos para transformar oportunidades em solucoes por meio de pensamento inovador, mentalidade agil e bom uso de dados, ajudando a LPC a se tornar mais centrada no cliente, enxuta, sustentavel e orientada por dados.",
    },
    { title: "Valor", text: "Agile." },
  ],
  pillars: [
    { title: "Cultura, Capacitacao e Educacao", text: "Disseminar cultura de inovacao dentro de LPC e auxiliar na capacitacao de colaboradores em novas ferramentas e metodologias voltadas para automacao, digitalizacao e data-driven." },
    { title: "Pesquisa e Desenvolvimento", text: "Explorar novas ferramentas, solucoes, tecnologias, novos skills e provas de conceito." },
    { title: "Desenvolvimentos", text: "Desenvolver e implementar solucoes relacionadas a digitalizacao e automacao de processos, incluindo ou nao prototipacoes." },
    { title: "Interacao com o Ecossistema", text: "Conectar com mercado, buscar parcerias, realizar benchmarking e criar interacoes com universidades e startups." },
    { title: "Data Management", text: "Gerenciar e disponibilizar dados." },
  ],
  teamMembers: [
    { name: "Gabriela Tartare", role: "Group Manager + Project Manager SAP", area: "Leadership", shortBio: "Conduz a visao da area e integra as frentes de entrega.", fullBio: "Lidera a area conectando estrategia, priorizacao e execucao. Atua como ponto de convergencia entre demandas do negocio, governanca e o time de entregas.", responsibilities: ["Direcionamento da area", "Priorizacao executiva", "Alinhamento com stakeholders"], tools: ["Gestao de portfolio", "Governanca", "Roadmaps"], contact: "Contato interno: TODO", photo: "/assets/gabriela.png" },
    { name: "Davi Gazola", role: "IT Support & Innovation", area: "Innovation", shortBio: "Apoia a operacao com foco em suporte e melhorias.", fullBio: "Atua na ponte entre suporte tecnico e oportunidades de inovacao, ajudando a transformar necessidades recorrentes em solucoes mais eficientes.", responsibilities: ["Suporte tecnico", "Levantamento de oportunidades", "Apoio a iniciativas"], tools: ["ITSM", "Power Platform", "Excel"], contact: "Contato interno: TODO", photo: "/assets/davi.png"},
    { name: "Joao Cerri", role: "LPC Lab Intern", area: "LPC Lab", shortBio: "Explora ideias, prototipos e aprendizados com a equipe.", fullBio: "Participa do desenvolvimento de solucoes e do apoio as iniciativas do laboratório, com foco em aprendizado rapido e entrega incremental.", responsibilities: ["Prototipacao", "Apoio a automacoes", "Documentacao"], tools: ["Power Apps", "Power Automate", "Python"], contact: "Contato interno: TODO", photo: "/assets/joao.png" },
    { name: "Marcos Passos", role: "LPC Lab Intern", area: "LPC Lab", shortBio: "Colabora com provas de conceito e validacao de ideias.", fullBio: "Atua em iniciativas do LPC Lab, contribuindo com experimentacao, desenvolvimento e suporte a validacao de hipoteses para novas solucoes.", responsibilities: ["PoCs", "Testes", "Apoio ao lab"], tools: ["Excel", "Power BI", "Scripts"], contact: "Contato interno: TODO", photo: "/assets/marcos.png" },
    { name: "Camila Morais", role: "CCT SAP + LPC Project Office", area: "Projects", shortBio: "Conecta projetos, SAP e acompanhamento de entregas.", fullBio: "Atua na articulacao entre projetos, SAP e acompanhamento de demandas, apoiando a organizacao de prazos, alinhamentos e entregas.", responsibilities: ["Apoio a projetos", "Interface SAP", "Acompanhamento"], tools: ["SAP", "Project tracking", "Excel"], contact: "Contato interno: TODO",photo: "/assets/camila.png" },
    { name: "Renato Dantas", role: "Customer Support SAP + Innovation", area: "Innovation", shortBio: "Une suporte a usuarios e oportunidades de inovacao.", fullBio: "Apoia usuarios em SAP e identifica possibilidades de melhoria, ajudando a transformar desvios e necessidades em iniciativas de valor.", responsibilities: ["Suporte SAP", "Analise de desvios", "Inovacao"], tools: ["SAP", "Power BI", "Automacoes"], contact: "Contato interno: TODO" ,photo: "/assets/renato.png"},
    { name: "Anastassia Oberlander", role: "Master Data SAP + Data Management", area: "Data Management", shortBio: "Zela por dados consistentes e disponibilizacao confiavel.", fullBio: "Atua com governanca e manutencao de dados mestres, apoiando a confiabilidade das informacoes usadas nas operacoes e nas decisoes.", responsibilities: ["Dados mestres", "Qualidade de dados", "Governanca"], tools: ["SAP", "Data management", "Excel"], contact: "Contato interno: TODO" ,photo: "/assets/anastassia.png"},
    { name: "Paulo Leite", role: "Transport SAP + Distribution Structure", area: "Transport", shortBio: "Apoia processos logísticos e estrutura de distribuicao.", fullBio: "Contribui com a sustentacao de processos de transporte e distribuicao, conectando operacao, estrutura e informacao.", responsibilities: ["Transportes", "Distribuicao", "Apoio funcional"], tools: ["SAP", "Planilhas", "Dashboards"], contact: "Contato interno: TODO" ,photo: "/assets/paulo.png"},
    { name: "Rodrigo Oliveira", role: "PO SAP + IT Coordination", area: "IT Coordination", shortBio: "Faz a coordinacao entre SAP e TI com visão de produto.", fullBio: "Atua na coordenacao de frentes de TI e SAP, apoiando alinhamentos, organizacao de demandas e conexao entre times.", responsibilities: ["Coordenação de TI", "SAP PO", "Priorização"], tools: ["SAP", "Kanban", "Roadmaps"], contact: "Contato interno: TODO" ,photo: "/assets/rodrigo.png"},
    { name: "Arthur Chetenki", role: "Sales & Invoice SAP", area: "SAP", shortBio: "Apoia processos de vendas e faturamento no SAP.", fullBio: "Contribui para a sustentacao e melhoria de processos de vendas e faturamento, com foco em confiabilidade operacional.", responsibilities: ["Vendas", "Faturamento", "Apoio SAP"], tools: ["SAP", "Excel", "BI"], contact: "Contato interno: TODO" ,photo: "/assets/arthur.png"},
    { name: "Leandro Tomazini", role: "Warehouse Out. SAP", area: "Warehouse", shortBio: "Atua em processos de expedicao e saida do armazem.", fullBio: "Apoia o fluxo de warehouse outbound, garantindo integracao entre processo, sistema e operação.", responsibilities: ["Expedicao", "Saida de estoque", "Apoio operacional"], tools: ["SAP", "Warehouse flows"], contact: "Contato interno: TODO" ,photo: "/assets/leandro.png"},
    { name: "Livia Bevilacqua", role: "Warehouse Inb. SAP", area: "Warehouse", shortBio: "Apoia entradas e recebimento de materiais no armazem.", fullBio: "Atua no processo inbound do warehouse, ajudando a manter a qualidade e a rastreabilidade das entradas.", responsibilities: ["Recebimento", "Entrada de estoque", "Apoio operacional"], tools: ["SAP", "Warehouse flows"], contact: "Contato interno: TODO",photo: "/assets/livia.png" },
    { name: "Vitor Padilha", role: "Planning & Procurement SAP", area: "Planning & Procurement", shortBio: "Suporta planejamento e compras com foco em processo.", fullBio: "Apoia planejamento e procurement, conectando necessidades de abastecimento, sistema e acompanhamento operacional.", responsibilities: ["Planejamento", "Compras", "Suporte SAP"], tools: ["SAP", "Excel", "Reports"], contact: "Contato interno: TODO",photo: "/assets/vitor.png" },
  ],
  quickLinks: [
    {
      category: "Canal",
      title: "Capacitação e Cultura de Inovação",
      description: "Solicite treinamentos, mentorias, pílulas de conhecimento ou iniciativas para disseminar cultura de inovação.",
      cta: "Abrir solicitação",
      url: "https://forms.cloud.microsoft/pages/responsepage.aspx?id=5GLAO52sF0y03TqtY3_xrOhUeybL7-JGrIsPzimmOlRURThWU1RGSUZESDgxMzZLSTIzS05NUU00RSQlQCN0PWcu&route=shorturl",
      chip: "Para todos",
      eta: "Resposta em até 2 dias úteis",
      highlight: false,
      icon: "education",
    },
    {
      category: "Principal",
      title: "Desenvolvimento e Chamados",
      description: "Solicite desenvolvimento de solução digital, automação, dashboard, melhoria de processo ou abertura de chamado relacionado.",
      cta: "Abrir chamado",
      url: "https://forms.cloud.microsoft/e/3CcZqVCywg",
      chip: "Para todos",
      eta: "Resposta em até 1 dia útil",
      highlight: true,
      icon: "settings",
    },
  ],
  timeline: [
    {
      year: "2020",
      title: "Criação da área",
      description: "Suporte passa a atender todo o LPC, não apenas WH.",
      highlights: ["Ampliação do escopo de atendimento", "Estruturação inicial da área"],
      impact: "Base para uma atuação mais próxima das áreas LPC.",
      learning: "A área começou a se posicionar como suporte ampliado para a operação.",
    },
    {
      year: "2021",
      title: "Reativação do LPC LAB",
      description: "Reativação do LPC LAB e início do DMA.",
      highlights: ["Retomada da frente de inovação", "Início das iniciativas ligadas ao DMA"],
      impact: "Fortalecimento da experimentação e da atuação em dados.",
      learning: "O laboratório voltou a ser um espaço de exploração e aprendizado aplicado.",
    },
    {
      year: "2022",
      title: "Mudança de foco",
      description:
        "Envolvimento da equipe LPC por meio da inovação e digitalização. Medição pela quantidade de iniciativas.",
      highlights: [
        "Maior envolvimento das áreas",
        "Foco em inovação e digitalização",
        "Medição por quantidade de iniciativas",
      ],
      impact: "Aproximação entre tecnologia, operação e melhoria contínua.",
      learning: "A colaboração passou a ser um fator central para ampliar o impacto.",
    },
    {
      year: "2023",
      title: "Novos pilares",
      description:
        "Preparação de usuários-chave em cada área LPC, liberação de capacidade da equipe LKLI para novas tecnologias e soluções mais complexas, sustentabilidade como driver e foco em dados, IA e ML.",
      highlights: [
        "Usuários-chave em cada área LPC",
        "Novas tecnologias e soluções mais complexas",
        "Sustentabilidade como driver",
        "Foco em dados, IA e Machine Learning",
      ],
      impact: "Expansão da maturidade digital e da cultura orientada por dados.",
      learning: "A área ganhou maturidade para atuar em soluções mais complexas e estratégicas.",
    },
    {
      year: "2024",
      title: "Inovação colaborativa",
      description: "Foco em inovação colaborativa e valor agregado. Medição pela economia de horas.",
      highlights: ["Inovação colaborativa", "Geração de valor agregado", "Medição por economia de horas"],
      impact: "Projetos mais conectados ao valor gerado para a operação.",
      learning: "Valor passou a ser medido de forma mais tangível para o negócio.",
    },
    {
      year: "2025",
      title: "Desenvolvimento e Inovação",
      description: "Área passa de Desenvolvimento para Desenvolvimento e Inovação, alinhada à estratégia 2025.",
      highlights: ["Reposicionamento da área", "Alinhamento com a estratégia 2025", "Fortalecimento da atuação em inovação"],
      impact: "Nova identidade para ampliar impacto, colaboração e visão estratégica.",
      learning: "A área consolidou um posicionamento mais claro entre desenvolvimento e inovação.",
    },
    {
      year: "2026",
      title: "Próxima fase",
      description: "Consolidação da jornada com foco em escala, inteligência aplicada e evolução contínua.",
      highlights: [
        "Soluções mais integradas",
        "Automações inteligentes",
        "Uso ampliado de dados, IA e Machine Learning",
        "Maior impacto nas áreas LPC",
      ],
      impact: "Evolução da área para soluções mais escaláveis e inteligentes.",
      learning: "A jornada aponta para escala com inteligência aplicada e evolução contínua.",
    },
  ],
  process: [
    { title: "Solicitacao", text: "Abertura via formulario com contexto, objetivo e resultado esperado.", badge: "Entrada" },
    { title: "Entrevista", text: "Entendimento da necessidade, do contexto e das dependencias.", badge: "Analise" },
    { title: "Classificacao", text: "Definicao do esforco e da complexidade da demanda.", badge: "Triagem" },
    { title: "Priorizacao", text: "Demandas High Effort seguem para priorizacao em lideranca.", badge: "High Effort" },
    { title: "Preparacao", text: "Organizacao de informacoes, requisitos e plano de entrega.", badge: "Setup" },
    { title: "Desenvolvimento", text: "Construcao da solucao com iteracoes curtas e foco em valor.", badge: "Build" },
    { title: "Documentacao", text: "Registro de uso, manutencao e orientacoes para suporte.", badge: "Docs" },
    { title: "Implementacao", text: "Publicacao, acompanhamento e estabilizacao da entrega.", badge: "Go-live" },
  ],
  faq: [
    { q: "Como abro uma solicitacao?", a: "Voce pode abrir uma solicitacao pelo formulario anexado no topo da pagina, informando o contexto da necessidade, o objetivo da demanda, a area envolvida e o resultado esperado. Com essas informacoes, o time consegue avaliar a solicitacao com mais agilidade e direcionar os proximos passos.", buttons: true },
    { q: "Quais servicos o time de Inovacao oferece?", a: "O time de Inovacao atua no desenvolvimento de solucoes digitais, automacoes, dashboards (BI's), melhorias de processos, aplicacao de mentorias, pilulas de conhecimento e treinamentos, solucao de desvios/chamados e apoio a implementacao de novas ideias. O objetivo e transformar oportunidades em solucoes praticas que gerem valor para a operacao e para o negocio." },
    { q: "Como funciona nosso processo?", a: "O processo de inovacao funciona da seguinte forma: os usuarios abrem as solicitacoes de desenvolvimento por meio do preenchimento de um formulario. Apos o envio, nosso time realiza uma entrevista para entender melhor a necessidade, o contexto e os objetivos da solicitacao. Em seguida, a demanda passa pela etapa de classificacao. Caso seja classificada como High Effort, ela segue para a etapa de priorizacao. Quando a iniciativa e iniciada, sao realizadas as etapas de preparacao, desenvolvimento, documentacao e implementacao." },
    { q: "Como as demandas sao priorizadas?", a: "As demandas sao avaliadas durante a reuniao de lideranca, na qual ocorre o processo de priorizacao das iniciativas. Cada area tem direito a priorizar uma iniciativa. E importante destacar que a priorizacao se aplica apenas as iniciativas classificadas como High Effort. Iniciativas classificadas como Medium Effort ou Low Effort podem ser puxadas assim que houver disponibilidade, sem necessidade de priorizacao formal." },
    { q: "Como acompanho o andamento da minha solicitacao?", a: "Apos o envio, o acompanhamento acontece pelos canais de comunicacao internos, como Teams ou Outlook. O solicitante e informado sobre o status da solicitacao, as etapas previstas e os responsaveis envolvidos no processo." },
    { q: "Em quais tecnologias temos atuacao?", a: "Power Apps, Power Automate, Power BI, Python, Machine Learning, IA, Excel, entre outras." },
  ],
};
